import type { ReportAnalysis } from "@/types";

export function generateMockReport(id: string, fileName: string): ReportAnalysis {
  const biomarkers = [
    {
      id: "hgb",
      name: "Hemoglobin",
      value: 11.2,
      unit: "g/dL",
      referenceRange: { min: 13.0, max: 17.0 },
      status: "low" as const,
      category: "Complete Blood Count",
    },
    {
      id: "wbc",
      name: "White Blood Cells",
      value: 7.5,
      unit: "×10³/µL",
      referenceRange: { min: 4.5, max: 11.0 },
      status: "normal" as const,
      category: "Complete Blood Count",
    },
    {
      id: "plt",
      name: "Platelets",
      value: 245,
      unit: "×10³/µL",
      referenceRange: { min: 150, max: 400 },
      status: "normal" as const,
      category: "Complete Blood Count",
    },
    {
      id: "rbc",
      name: "Red Blood Cells",
      value: 4.1,
      unit: "×10⁶/µL",
      referenceRange: { min: 4.5, max: 5.5 },
      status: "low" as const,
      category: "Complete Blood Count",
    },
    {
      id: "hct",
      name: "Hematocrit",
      value: 38.5,
      unit: "%",
      referenceRange: { min: 38.3, max: 48.6 },
      status: "normal" as const,
      category: "Complete Blood Count",
    },
    {
      id: "glu",
      name: "Fasting Glucose",
      value: 112,
      unit: "mg/dL",
      referenceRange: { min: 70, max: 100 },
      status: "high" as const,
      category: "Metabolic Panel",
    },
    {
      id: "hba1c",
      name: "HbA1c",
      value: 6.1,
      unit: "%",
      referenceRange: { min: 4.0, max: 5.6 },
      status: "high" as const,
      category: "Metabolic Panel",
    },
    {
      id: "tc",
      name: "Total Cholesterol",
      value: 242,
      unit: "mg/dL",
      referenceRange: { min: 0, max: 200 },
      status: "high" as const,
      category: "Lipid Panel",
    },
    {
      id: "ldl",
      name: "LDL Cholesterol",
      value: 165,
      unit: "mg/dL",
      referenceRange: { min: 0, max: 100 },
      status: "high" as const,
      category: "Lipid Panel",
    },
    {
      id: "hdl",
      name: "HDL Cholesterol",
      value: 42,
      unit: "mg/dL",
      referenceRange: { min: 40, max: 60 },
      status: "normal" as const,
      category: "Lipid Panel",
    },
    {
      id: "trig",
      name: "Triglycerides",
      value: 178,
      unit: "mg/dL",
      referenceRange: { min: 0, max: 150 },
      status: "high" as const,
      category: "Lipid Panel",
    },
    {
      id: "tsh",
      name: "TSH",
      value: 5.8,
      unit: "µIU/mL",
      referenceRange: { min: 0.4, max: 4.0 },
      status: "high" as const,
      category: "Thyroid Panel",
    },
    {
      id: "ft4",
      name: "Free T4",
      value: 0.9,
      unit: "ng/dL",
      referenceRange: { min: 0.8, max: 1.8 },
      status: "normal" as const,
      category: "Thyroid Panel",
    },
    {
      id: "vitd",
      name: "Vitamin D (25-OH)",
      value: 18,
      unit: "ng/mL",
      referenceRange: { min: 30, max: 100 },
      status: "low" as const,
      category: "Vitamins & Minerals",
    },
    {
      id: "b12",
      name: "Vitamin B12",
      value: 310,
      unit: "pg/mL",
      referenceRange: { min: 200, max: 900 },
      status: "normal" as const,
      category: "Vitamins & Minerals",
    },
    {
      id: "iron",
      name: "Serum Iron",
      value: 55,
      unit: "µg/dL",
      referenceRange: { min: 60, max: 170 },
      status: "low" as const,
      category: "Vitamins & Minerals",
    },
    {
      id: "ferr",
      name: "Ferritin",
      value: 18,
      unit: "ng/mL",
      referenceRange: { min: 20, max: 250 },
      status: "low" as const,
      category: "Vitamins & Minerals",
    },
    {
      id: "cre",
      name: "Creatinine",
      value: 1.0,
      unit: "mg/dL",
      referenceRange: { min: 0.7, max: 1.3 },
      status: "normal" as const,
      category: "Kidney Function",
    },
    {
      id: "bun",
      name: "BUN",
      value: 18,
      unit: "mg/dL",
      referenceRange: { min: 7, max: 20 },
      status: "normal" as const,
      category: "Kidney Function",
    },
    {
      id: "alt",
      name: "ALT (SGPT)",
      value: 52,
      unit: "U/L",
      referenceRange: { min: 7, max: 40 },
      status: "high" as const,
      category: "Liver Function",
    },
    {
      id: "ast",
      name: "AST (SGOT)",
      value: 35,
      unit: "U/L",
      referenceRange: { min: 8, max: 40 },
      status: "normal" as const,
      category: "Liver Function",
    },
    {
      id: "na",
      name: "Sodium",
      value: 141,
      unit: "mEq/L",
      referenceRange: { min: 136, max: 145 },
      status: "normal" as const,
      category: "Electrolytes",
    },
    {
      id: "k",
      name: "Potassium",
      value: 4.2,
      unit: "mEq/L",
      referenceRange: { min: 3.5, max: 5.0 },
      status: "normal" as const,
      category: "Electrolytes",
    },
  ];

  const summary = {
    total: biomarkers.length,
    normal: biomarkers.filter((b) => b.status === "normal").length,
    low: biomarkers.filter((b) => b.status === "low").length,
    high: biomarkers.filter((b) => b.status === "high").length,
    critical: biomarkers.filter((b) => b.status === "critical").length,
  };

  const recommendations = [
    {
      id: "rec-1",
      biomarkerName: "Hemoglobin",
      type: "dietary" as const,
      title: "Increase Iron-Rich Foods",
      description:
        "Your hemoglobin is below normal range. Include iron-rich foods like spinach, red meat, lentils, and fortified cereals in your diet. Pair with vitamin C sources (citrus fruits, bell peppers) to boost iron absorption.",
      priority: "high" as const,
    },
    {
      id: "rec-2",
      biomarkerName: "Vitamin D (25-OH)",
      type: "lifestyle" as const,
      title: "Sun Exposure & Supplementation",
      description:
        "Vitamin D is significantly low. Get 15–20 minutes of direct sunlight daily. Consider foods like fatty fish (salmon, mackerel), fortified milk, and egg yolks. A vitamin D3 supplement (1000–2000 IU/day) may be beneficial — discuss dosage with your doctor.",
      priority: "high" as const,
    },
    {
      id: "rec-3",
      biomarkerName: "Total Cholesterol",
      type: "dietary" as const,
      title: "Heart-Healthy Diet Adjustments",
      description:
        "Your total and LDL cholesterol are elevated. Reduce saturated fats (red meat, full-fat dairy, fried foods). Increase omega-3 fatty acids (salmon, walnuts, flaxseed) and soluble fiber (oats, beans, apples).",
      priority: "high" as const,
    },
    {
      id: "rec-4",
      biomarkerName: "TSH",
      type: "specialist" as const,
      title: "Consult an Endocrinologist",
      description:
        "Your TSH is elevated above the normal range, which may indicate hypothyroidism. Schedule an appointment with an endocrinologist for a comprehensive thyroid evaluation including Free T3 and thyroid antibody tests.",
      priority: "urgent" as const,
    },
    {
      id: "rec-5",
      biomarkerName: "Fasting Glucose",
      type: "lifestyle" as const,
      title: "Blood Sugar Management",
      description:
        "Fasting glucose and HbA1c indicate pre-diabetic levels. Regular aerobic exercise (150 min/week), limiting refined carbohydrates and sugary beverages, and maintaining a healthy weight can help normalize blood sugar levels.",
      priority: "high" as const,
    },
    {
      id: "rec-6",
      biomarkerName: "Ferritin",
      type: "dietary" as const,
      title: "Replenish Iron Stores",
      description:
        "Low ferritin indicates depleted iron stores. Consume heme iron sources (lean red meat, organ meats) and non-heme sources (tofu, dark leafy greens, dried apricots). Avoid tea/coffee with meals as they inhibit absorption.",
      priority: "medium" as const,
    },
    {
      id: "rec-7",
      biomarkerName: "ALT (SGPT)",
      type: "lifestyle" as const,
      title: "Liver Health Precautions",
      description:
        "ALT is mildly elevated. Reduce alcohol intake, maintain a healthy weight, and limit processed foods. If this is persistent, follow up with a hepatologist for further evaluation.",
      priority: "medium" as const,
    },
  ];

  return {
    id,
    fileName,
    uploadedAt: new Date().toISOString(),
    biomarkers,
    summary,
    recommendations,
  };
}

// Pre-generated mock for the demo dashboard
export const DEMO_REPORT = generateMockReport("demo-001", "sample_blood_report.pdf");
